export default {
  input: 'preload.js',
  treeshake: false,
  external: ['fs'],
  output: {
    file: 'preload.bundle.js',
    format: 'es',
    exports: 'default',
    intro: '// This file is generated by Rollup, need to replace `export {xxx as default}` to `export default xxx` manually',
  },
};
